# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ef3521d68899f3b1c1d118c21fb75f7037e06570e2bf8baedb9a37c33d1ea5e5438303defc4daf340abcb58e2cd38c7f328079ef39e84eded23a8391c5f9c90

test:
  secret_key_base: 0ff773848ae2d179bb24daf5812fc2a9b8e816771c60de414a95a32e92d7eca578e29d50b725f292433c96346133f701b3248328d98f28ce7da12042cdb32993

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
